language: python
python:
  - "pypy"
  - "2.7"
# command to install dependencies
install: "sudo apt-get install -y libgeoip-dev && pip install -r requirements.txt && pip install -r dev-requirements.txt"
# command to run tests
script:
    make coverage
after_success:
    coveralls
